# Generated by Django 4.0 on 2024-09-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report_card_genration',
            field=models.DateField(auto_now_add=True),
        ),
    ]
